CREATE DATABASE IF NOT EXISTS `cfpt_maker` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, FILE, INDEX, ALTER, CREATE TEMPORARY TABLES, EXECUTE, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER, DELETE HISTORY ON *.* TO 'GreenMario'@'localhost' IDENTIFIED BY PASSWORD '*D8A1D5237AEAC8A1F1437679826B9167928BC7B5';
